// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VitrineApi.Data;

#nullable disable

namespace VitrineApi.Migrations
{
    [DbContext(typeof(VitrineDBContext))]
    [Migration("20251122165613_AddStatusPedidoEnum")]
    partial class AddStatusPedidoEnum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LojistaAuth", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpf_Cnpj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("VitrineApi.Models.CategoriaLoja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Imagem")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CategoriaLoja");
                });

            modelBuilder.Entity("VitrineApi.Models.CategoriaProduto", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("IdCategoriaLoja")
                        .HasColumnType("int");

                    b.Property<byte[]>("Imagem")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoriaLoja");

                    b.ToTable("CategoriaProduto");
                });

            modelBuilder.Entity("VitrineApi.Models.Cliente", b =>
                {
                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Cpf")
                        .HasName("PK_Cliente_1");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("VitrineApi.Models.EnderecoEntrega", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CpfCliente")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CpfCliente" }, "IX_EnderecoEntrega_IdCliente");

                    b.ToTable("EnderecoEntrega");
                });

            modelBuilder.Entity("VitrineApi.Models.ItensPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdPedido")
                        .HasColumnType("int");

                    b.Property<int>("IdProduto")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoTotal")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdPedido" }, "IX_ItensPedido_IdPedido");

                    b.HasIndex(new[] { "IdProduto" }, "IX_ItensPedido_IdProduto");

                    b.ToTable("ItensPedido");
                });

            modelBuilder.Entity("VitrineApi.Models.Layout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Layout");
                });

            modelBuilder.Entity("VitrineApi.Models.Loja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Avaliacao")
                        .HasColumnType("decimal(3, 1)");

                    b.Property<string>("Cpf_Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdLayout")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF__Loja__IdLayout__693CA210");

                    b.Property<int>("IdTema")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF__Loja__IdTema__6A30C649");

                    b.Property<string>("Logotipo")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NomeLoja")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Subdominio")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF__Loja__Subdominio__68487DD7");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.HasIndex(new[] { "Cpf_Cnpj" }, "IX_Loja_Cpf");

                    b.HasIndex(new[] { "IdLayout" }, "IX_Loja_IdLayout");

                    b.HasIndex(new[] { "IdTema" }, "IX_Loja_IdTema");

                    b.ToTable("Loja");
                });

            modelBuilder.Entity("VitrineApi.Models.Lojista", b =>
                {
                    b.Property<string>("Cpf_Cnpj")
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Cpf_Cnpj");

                    b.ToTable("Lojista");
                });

            modelBuilder.Entity("VitrineApi.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoRastreamento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CpfCliente")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("datetime");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("FreteValor")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("IdEnderecoEntrega")
                        .HasColumnType("int");

                    b.Property<int>("IdLoja")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CpfCliente" }, "IX_Pedido_IdCliente");

                    b.HasIndex(new[] { "IdEnderecoEntrega" }, "IX_Pedido_IdEnderecoEntrega");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("VitrineApi.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Altura")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<byte>("Ativo")
                        .HasColumnType("tinyint");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.Property<int>("IdCategoriaProduto")
                        .HasColumnType("int");

                    b.Property<int>("IdLoja")
                        .HasColumnType("int");

                    b.Property<string>("Imagem")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Largura")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Profundidade")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("ValorPromocional")
                        .HasColumnType("decimal(10, 4)");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(10, 4)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdCategoriaProduto" }, "IX_Produto_IdCategoriaProduto");

                    b.HasIndex(new[] { "IdLoja" }, "IX_Produto_IdLoja");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("VitrineApi.Models.Tema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Tema");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LojistaAuth", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LojistaAuth", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LojistaAuth", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LojistaAuth", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VitrineApi.Models.CategoriaProduto", b =>
                {
                    b.HasOne("VitrineApi.Models.CategoriaLoja", "IdCategoriaLojaNavigation")
                        .WithMany("CategoriaProduto")
                        .HasForeignKey("IdCategoriaLoja")
                        .IsRequired()
                        .HasConstraintName("FK_CategoriaProduto_CategoriaLoja");

                    b.Navigation("IdCategoriaLojaNavigation");
                });

            modelBuilder.Entity("VitrineApi.Models.EnderecoEntrega", b =>
                {
                    b.HasOne("VitrineApi.Models.Cliente", "CpfClienteNavigation")
                        .WithMany("EnderecoEntrega")
                        .HasForeignKey("CpfCliente")
                        .IsRequired()
                        .HasConstraintName("FK_EnderecoEntrega_Cliente1");

                    b.Navigation("CpfClienteNavigation");
                });

            modelBuilder.Entity("VitrineApi.Models.ItensPedido", b =>
                {
                    b.HasOne("VitrineApi.Models.Pedido", "IdPedidoNavigation")
                        .WithMany("ItensPedido")
                        .HasForeignKey("IdPedido")
                        .IsRequired()
                        .HasConstraintName("FK_ItensPedido_Pedido");

                    b.HasOne("VitrineApi.Models.Produto", "IdProdutoNavigation")
                        .WithMany("ItensPedido")
                        .HasForeignKey("IdProduto")
                        .IsRequired()
                        .HasConstraintName("FK_ItensPedido_Produto");

                    b.Navigation("IdPedidoNavigation");

                    b.Navigation("IdProdutoNavigation");
                });

            modelBuilder.Entity("VitrineApi.Models.Loja", b =>
                {
                    b.HasOne("VitrineApi.Models.Lojista", "Cpf_CnpjNavigation")
                        .WithMany("Loja")
                        .HasForeignKey("Cpf_Cnpj")
                        .IsRequired()
                        .HasConstraintName("FK_Loja_Lojista");

                    b.HasOne("VitrineApi.Models.CategoriaLoja", "IdCategoriaNavigation")
                        .WithMany("Loja")
                        .HasForeignKey("IdCategoria")
                        .IsRequired()
                        .HasConstraintName("FK_Loja_CategoriaLoja");

                    b.HasOne("VitrineApi.Models.Layout", "IdLayoutNavigation")
                        .WithMany("Loja")
                        .HasForeignKey("IdLayout")
                        .IsRequired()
                        .HasConstraintName("FK_Loja_Layout");

                    b.HasOne("VitrineApi.Models.Tema", "IdTemaNavigation")
                        .WithMany("Loja")
                        .HasForeignKey("IdTema")
                        .IsRequired()
                        .HasConstraintName("FK_Loja_Tema");

                    b.Navigation("Cpf_CnpjNavigation");

                    b.Navigation("IdCategoriaNavigation");

                    b.Navigation("IdLayoutNavigation");

                    b.Navigation("IdTemaNavigation");
                });

            modelBuilder.Entity("VitrineApi.Models.Pedido", b =>
                {
                    b.HasOne("VitrineApi.Models.Cliente", "CpfClienteNavigation")
                        .WithMany("Pedido")
                        .HasForeignKey("CpfCliente")
                        .IsRequired()
                        .HasConstraintName("FK_Pedido_Cliente1");

                    b.HasOne("VitrineApi.Models.EnderecoEntrega", "IdEnderecoEntregaNavigation")
                        .WithMany("Pedido")
                        .HasForeignKey("IdEnderecoEntrega")
                        .IsRequired()
                        .HasConstraintName("FK_Pedido_EnderecoEntrega");

                    b.Navigation("CpfClienteNavigation");

                    b.Navigation("IdEnderecoEntregaNavigation");
                });

            modelBuilder.Entity("VitrineApi.Models.Produto", b =>
                {
                    b.HasOne("VitrineApi.Models.CategoriaProduto", "IdCategoriaProdutoNavigation")
                        .WithMany("Produto")
                        .HasForeignKey("IdCategoriaProduto")
                        .IsRequired()
                        .HasConstraintName("FK_Produto_CategoriaProduto");

                    b.HasOne("VitrineApi.Models.Loja", "IdLojaNavigation")
                        .WithMany("Produto")
                        .HasForeignKey("IdLoja")
                        .IsRequired()
                        .HasConstraintName("FK_Produto_Loja");

                    b.Navigation("IdCategoriaProdutoNavigation");

                    b.Navigation("IdLojaNavigation");
                });

            modelBuilder.Entity("VitrineApi.Models.CategoriaLoja", b =>
                {
                    b.Navigation("CategoriaProduto");

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("VitrineApi.Models.CategoriaProduto", b =>
                {
                    b.Navigation("Produto");
                });

            modelBuilder.Entity("VitrineApi.Models.Cliente", b =>
                {
                    b.Navigation("EnderecoEntrega");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("VitrineApi.Models.EnderecoEntrega", b =>
                {
                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("VitrineApi.Models.Layout", b =>
                {
                    b.Navigation("Loja");
                });

            modelBuilder.Entity("VitrineApi.Models.Loja", b =>
                {
                    b.Navigation("Produto");
                });

            modelBuilder.Entity("VitrineApi.Models.Lojista", b =>
                {
                    b.Navigation("Loja");
                });

            modelBuilder.Entity("VitrineApi.Models.Pedido", b =>
                {
                    b.Navigation("ItensPedido");
                });

            modelBuilder.Entity("VitrineApi.Models.Produto", b =>
                {
                    b.Navigation("ItensPedido");
                });

            modelBuilder.Entity("VitrineApi.Models.Tema", b =>
                {
                    b.Navigation("Loja");
                });
#pragma warning restore 612, 618
        }
    }
}
