// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using VitrineApi.Models;

namespace VitrineApi.Data
{
    public partial class VitrineDBContext : IdentityDbContext<LojistaAuth>
    {
        public VitrineDBContext(DbContextOptions<VitrineDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<CategoriaProduto> CategoriaProduto { get; set; }

        public virtual DbSet<Loja> Loja { get; set; }

        public virtual DbSet<Lojista> Lojista { get; set; }

        public virtual DbSet<Produto> Produto { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<Loja>(entity =>
            {
                entity.HasOne(d => d.CpfNavigation).WithMany(p => p.Loja)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Loja_Lojista");
            });

            modelBuilder.Entity<Produto>(entity =>
            {
                entity.HasOne(d => d.IdCategoriaProdutoNavigation).WithMany(p => p.Produto)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Produto_CategoriaProduto");

                entity.HasOne(d => d.IdLojaNavigation).WithMany(p => p.Produto)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Produto_Loja");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}