// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using VitrineApi.Models;

namespace VitrineApi.Data;

public partial class VitrineDBContext : IdentityDbContext<LojistaAuth>
{
    public VitrineDBContext(DbContextOptions<VitrineDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CategoriaLoja> CategoriaLoja { get; set; }

    public virtual DbSet<CategoriaProduto> CategoriaProduto { get; set; }

    public virtual DbSet<Cliente> Cliente { get; set; }

    public virtual DbSet<EnderecoEntrega> EnderecoEntrega { get; set; }

    public virtual DbSet<EnderecoLojista> EnderecoLojista { get; set; }

    public virtual DbSet<ItensPedido> ItensPedido { get; set; }

    public virtual DbSet<Layout> Layout { get; set; }

    public virtual DbSet<Loja> Loja { get; set; }

    public virtual DbSet<Lojista> Lojista { get; set; }

    public virtual DbSet<Pedido> Pedido { get; set; }

    public virtual DbSet<Produto> Produto { get; set; }

    public virtual DbSet<Tema> Tema { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<CategoriaProduto>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.IdCategoriaLojaNavigation).WithMany(p => p.CategoriaProduto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CategoriaProduto_CategoriaLoja");
        });

        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.HasKey(e => e.Cpf).HasName("PK_Cliente_1");
        });

        modelBuilder.Entity<EnderecoEntrega>(entity =>
        {
            entity.HasOne(d => d.CpfClienteNavigation).WithMany(p => p.EnderecoEntrega)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EnderecoEntrega_Cliente1");
        });

        modelBuilder.Entity<EnderecoLojista>(entity =>
        {
            entity.HasOne(d => d.Cpf_CnpjLojistaNavigation).WithMany(p => p.EnderecoLojista)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EnderecoLojista_Lojista");
        });

        modelBuilder.Entity<ItensPedido>(entity =>
        {
            entity.HasOne(d => d.IdPedidoNavigation).WithMany(p => p.ItensPedido)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ItensPedido_Pedido");

            entity.HasOne(d => d.IdProdutoNavigation).WithMany(p => p.ItensPedido)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ItensPedido_Produto");
        });

        modelBuilder.Entity<Loja>(entity =>
        {
            entity.Property(e => e.IdLayout).HasAnnotation("Relational:DefaultConstraintName", "DF__Loja__IdLayout__693CA210");
            entity.Property(e => e.IdTema).HasAnnotation("Relational:DefaultConstraintName", "DF__Loja__IdTema__6A30C649");
            entity.Property(e => e.Subdominio)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Loja__Subdominio__68487DD7");

            entity.HasOne(d => d.Cpf_CnpjNavigation).WithMany(p => p.Loja)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Loja_Lojista");

            entity.HasOne(d => d.IdCategoriaNavigation).WithMany(p => p.Loja)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Loja_CategoriaLoja");

            entity.HasOne(d => d.IdLayoutNavigation).WithMany(p => p.Loja)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Loja_Layout");

            entity.HasOne(d => d.IdTemaNavigation).WithMany(p => p.Loja)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Loja_Tema");
        });

        modelBuilder.Entity<Pedido>(entity =>
        {
            entity.HasOne(d => d.CpfClienteNavigation).WithMany(p => p.Pedido)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Pedido_Cliente1");

            entity.HasOne(d => d.IdEnderecoEntregaNavigation).WithMany(p => p.Pedido)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Pedido_EnderecoEntrega");
        });

        modelBuilder.Entity<Produto>(entity =>
        {
            entity.HasOne(d => d.IdCategoriaProdutoNavigation).WithMany(p => p.Produto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Produto_CategoriaProduto");

            entity.HasOne(d => d.IdLojaNavigation).WithMany(p => p.Produto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Produto_Loja");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}