// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VitrineApi.Models;

public partial class Loja
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string NomeLoja { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string CategoriaLoja { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Tema { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Layout { get; set; }

    [Required]
    [StringLength(11)]
    [Unicode(false)]
    public string Cpf { get; set; }

    [StringLength(14)]
    [Unicode(false)]
    public string Cnpj { get; set; }

    [ForeignKey("Cpf")]
    [InverseProperty("Loja")]
    public virtual Lojista CpfNavigation { get; set; }

    [InverseProperty("IdLojaNavigation")]
    public virtual ICollection<Produto> Produto { get; set; } = new List<Produto>();
}