// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VitrineApi.Models;

public partial class CategoriaLoja
{
    public int Id { get; set; }

    public string Titulo { get; set; }

    public byte[] Imagem { get; set; }

    public virtual ICollection<Loja> Loja { get; set; } = new List<Loja>();
}