// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VitrineApi.Models;

public partial class Cliente
{
    public int Id { get; set; }

    public string NomeCompleto { get; set; }

    public string Email { get; set; }

    public string Telefone { get; set; }

    public DateTime CriadoEm { get; set; }

    public virtual ICollection<EnderecoEntrega> EnderecoEntrega { get; set; } = new List<EnderecoEntrega>();

    public virtual ICollection<Pedido> Pedido { get; set; } = new List<Pedido>();
}