// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VitrineApi.Models;

public partial class Cliente
{
    [Key]
    [StringLength(11)]
    [Unicode(false)]
    public string Cpf { get; set; }

    [Required]
    [StringLength(200)]
    public string NomeCompleto { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Email { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string Telefone { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DataCriacao { get; set; }

    [InverseProperty("CpfClienteNavigation")]
    public virtual ICollection<EnderecoEntrega> EnderecoEntrega { get; set; } = new List<EnderecoEntrega>();

    [InverseProperty("CpfClienteNavigation")]
    public virtual ICollection<Pedido> Pedido { get; set; } = new List<Pedido>();
}