// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VitrineApi.Models;

public partial class EnderecoLojista
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(14)]
    [Unicode(false)]
    public string Cpf_CnpjLojista { get; set; }

    [Required]
    [StringLength(200)]
    public string Logradouro { get; set; }

    [Required]
    [StringLength(5)]
    public string Numero { get; set; }

    [StringLength(100)]
    public string Complemento { get; set; }

    [Required]
    [StringLength(100)]
    public string Bairro { get; set; }

    [Required]
    [StringLength(100)]
    public string Cidade { get; set; }

    [Required]
    [StringLength(100)]
    public string Estado { get; set; }

    [Required]
    [StringLength(20)]
    public string Cep { get; set; }

    [ForeignKey("Cpf_CnpjLojista")]
    [InverseProperty("EnderecoLojista")]
    public virtual Lojista Cpf_CnpjLojistaNavigation { get; set; }
}