// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VitrineApi.Models;

[Index("CpfCliente", Name = "IX_EnderecoEntrega_IdCliente")]
public partial class EnderecoEntrega
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(11)]
    [Unicode(false)]
    public string CpfCliente { get; set; }

    [Required]
    [StringLength(200)]
    public string Logradouro { get; set; }

    [Required]
    [StringLength(5)]
    public string Numero { get; set; }

    [StringLength(100)]
    public string Complemento { get; set; }

    [Required]
    [StringLength(100)]
    public string Bairro { get; set; }

    [Required]
    [StringLength(100)]
    public string Cidade { get; set; }

    [Required]
    [StringLength(100)]
    public string Estado { get; set; }

    [Required]
    [StringLength(20)]
    public string Cep { get; set; }

    [ForeignKey("CpfCliente")]
    [InverseProperty("EnderecoEntrega")]
    public virtual Cliente CpfClienteNavigation { get; set; }

    [InverseProperty("IdEnderecoEntregaNavigation")]
    public virtual ICollection<Pedido> Pedido { get; set; } = new List<Pedido>();
}