// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VitrineApi.Models;

public partial class ItensPedido
{
    public int Id { get; set; }

    public int IdPedido { get; set; }

    public int IdProduto { get; set; }

    public string NomeProduto { get; set; }

    public int Quantidade { get; set; }

    public decimal PrecoUnitario { get; set; }

    public decimal Total { get; set; }

    public virtual Pedido IdPedidoNavigation { get; set; }

    public virtual Produto IdProdutoNavigation { get; set; }
}