// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VitrineApi.Models;

public partial class Loja
{
    public int Id { get; set; }

    public string NomeLoja { get; set; }

    public string Cpf { get; set; }

    public string Cnpj { get; set; }

    public string Subdominio { get; set; }

    public int IdLayout { get; set; }

    public int IdTema { get; set; }

    public string Descricao { get; set; }

    public decimal? Avaliacao { get; set; }

    public string Logotipo { get; set; }

    public int IdCategoria { get; set; }

    public virtual Lojista CpfNavigation { get; set; }

    public virtual CategoriaLoja IdCategoriaNavigation { get; set; }

    public virtual Layout IdLayoutNavigation { get; set; }

    public virtual Tema IdTemaNavigation { get; set; }

    public virtual ICollection<Produto> Produto { get; set; } = new List<Produto>();
}