// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VitrineApi.Models;

public partial class Lojista
{
    [Key]
    [StringLength(14)]
    [Unicode(false)]
    public string Cpf_Cnpj { get; set; }

    [Required]
    [StringLength(255)]
    public string NomeCompleto { get; set; }

    public DateOnly DataNascimento { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Email { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Telefone { get; set; }

    [InverseProperty("Cpf_CnpjLojistaNavigation")]
    public virtual ICollection<EnderecoLojista> EnderecoLojista { get; set; } = new List<EnderecoLojista>();

    [InverseProperty("Cpf_CnpjNavigation")]
    public virtual ICollection<Loja> Loja { get; set; } = new List<Loja>();
}