// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace VitrineApi.Models;

public partial class Lojista
{
    [Key]
    [StringLength(11)]
    [Unicode(false)]
    public string Cpf { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string NomeCompleto { get; set; }

    public DateOnly DataNascimento { get; set; }

    [StringLength(11)]
    [Unicode(false)]
    public string Celular { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string Email { get; set; }

    [InverseProperty("CpfNavigation")]
    public virtual ICollection<Loja> Loja { get; set; } = new List<Loja>();
}