// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VitrineApi.Models;

public partial class Lojista
{
    public string Cpf { get; set; }

    public string NomeCompleto { get; set; }

    public DateOnly DataNascimento { get; set; }

    public string Email { get; set; }

    public string Telefone { get; set; }

    public virtual ICollection<Loja> Loja { get; set; } = new List<Loja>();
}