// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VitrineApi.Models;

public partial class Pedido
{
    public int Id { get; set; }

    public int IdLoja { get; set; }

    public int IdCliente { get; set; }

    public int IdEnderecoEntrega { get; set; }

    public DateTime DataCriacao { get; set; }

    public string Status { get; set; }

    public decimal ValorTotal { get; set; }

    public decimal FreteValor { get; set; }

    public string FormaPagamento { get; set; }

    public string CodigoRastreamento { get; set; }

    public DateTime DataPagamento { get; set; }

    public DateTime DataEnvio { get; set; }

    public string Observacoes { get; set; }

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual EnderecoEntrega IdEnderecoEntregaNavigation { get; set; }

    public virtual ICollection<ItensPedido> ItensPedido { get; set; } = new List<ItensPedido>();
}