// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using VitrineApi.Enums;

namespace VitrineApi.Models;

[Index("CpfCliente", Name = "IX_Pedido_IdCliente")]
[Index("IdEnderecoEntrega", Name = "IX_Pedido_IdEnderecoEntrega")]
public partial class Pedido
{
    [Key]
    public int Id { get; set; }

    public int IdLoja { get; set; }

    [Required]
    [StringLength(11)]
    [Unicode(false)]
    public string CpfCliente { get; set; }

    public int IdEnderecoEntrega { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DataPedido { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public StatusPedido Status { get; set; }

    [Column(TypeName = "decimal(18, 4)")]
    public decimal ValorTotal { get; set; }

    [Column(TypeName = "decimal(18, 4)")]
    public decimal FreteValor { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string FormaPagamento { get; set; }

    [StringLength(50)]
    public string CodigoRastreamento { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataPagamento { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataEnvio { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DataEntrega { get; set; }

    [StringLength(500)]
    public string Observacoes { get; set; }

    [ForeignKey("CpfCliente")]
    [InverseProperty("Pedido")]
    public virtual Cliente CpfClienteNavigation { get; set; }

    [ForeignKey("IdEnderecoEntrega")]
    [InverseProperty("Pedido")]
    public virtual EnderecoEntrega IdEnderecoEntregaNavigation { get; set; }

    [InverseProperty("IdPedidoNavigation")]
    public virtual ICollection<ItensPedido> ItensPedido { get; set; } = new List<ItensPedido>();
}