// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VitrineApi.Models;

[Index("IdCliente", Name = "IX_Pedido_IdCliente")]
[Index("IdEnderecoEntrega", Name = "IX_Pedido_IdEnderecoEntrega")]
public partial class Pedido
{
    [Key]
    public int Id { get; set; }

    public int IdLoja { get; set; }

    public int IdCliente { get; set; }

    public int IdEnderecoEntrega { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DataCriacao { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string Status { get; set; }

    [Column(TypeName = "decimal(18, 4)")]
    public decimal ValorTotal { get; set; }

    [Column(TypeName = "decimal(18, 4)")]
    public decimal FreteValor { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string FormaPagamento { get; set; }

    [StringLength(50)]
    public string CodigoRastreamento { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DataPagamento { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DataEnvio { get; set; }

    [StringLength(500)]
    public string Observacoes { get; set; }

    [ForeignKey("IdCliente")]
    [InverseProperty("Pedido")]
    public virtual Cliente IdClienteNavigation { get; set; }

    [ForeignKey("IdEnderecoEntrega")]
    [InverseProperty("Pedido")]
    public virtual EnderecoEntrega IdEnderecoEntregaNavigation { get; set; }

    [InverseProperty("IdPedidoNavigation")]
    public virtual ICollection<ItensPedido> ItensPedido { get; set; } = new List<ItensPedido>();
}