// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VitrineApi.Models;

public partial class Tema
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Titulo { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Descricao { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string ImagemUrl { get; set; }

    [InverseProperty("IdTemaNavigation")]
    public virtual ICollection<Loja> Loja { get; set; } = new List<Loja>();
}